### Basic Rule based Scoring

In [65]:
import pandas as pd
import numpy as np
import re

In [66]:
file_path="AutoEIT Sample Transcriptions for Scoring.xlsx"
xls = pd.ExcelFile(file_path)
sheet_names = xls.sheet_names
print(sheet_names)

['Info', '38001-1A', '38002-2A', '38004-2A', '38006-2A']

In [72]:
df=pd.read_excel(xls,sheet_name=sheet_names[1])
df.head()

,Sentence,Stimulus,Transcription Rater 1,Score
0,1,Quiero cortarme el pelo (7),Quiero cortarme el pelo,NaN
1,2,El libro está en la mesa (7),El libro está en la mesa,NaN
2,3,El carro lo tiene Pedro (8),El carro lo tiene Pedro,NaN
3,4,El se ducha cada mañana (9),El se ducha cada mañana,NaN
4,5,¿Qué dice usted que va a hacer hoy? (9),Que dices ustedes se que van a hacer hoy?,NaN

In [68]:
def preprocess(text):
    if pd.isna(text):
        return "";
    text=text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text=re.sub(r'[^\w\s]','',text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [69]:
df["clean_stimulus"]=df["Stimulus"].apply(preprocess)
df["clean_original"]=df["Transcription Rater 1"].apply(preprocess)
df.head()

,Sentence,Stimulus,Transcription Rater 1,Score,clean_stimulus,clean_original
0,1,Quiero cortarme el pelo (7),Quiero cortarme mi pelo,NaN,quiero cortarme el pelo 7,quiero cortarme mi pelo
1,2,El libro está en la mesa (7),El libro [pause] está en la mesa,NaN,el libro está en la mesa 7,el libro está en la mesa
2,3,El carro lo tiene Pedro (8),E-[gibberish] perro,NaN,el carro lo tiene pedro 8,e perro
3,4,El se ducha cada mañana (9),El se lucha cada mañana,NaN,el se ducha cada mañana 9,el se lucha cada mañana
4,5,¿Qué dice usted que va a hacer hoy? (9),¿Qué [gibberish] que vas estoy?,NaN,qué dice usted que va a hacer hoy 9,qué que vas estoy

In [44]:
def word_overlap(s1, s2):
    set1 = set(s1.split())
    set2 = set(s2.split())
    if len(set1) == 0:
        return 0
    return len(set1 & set2) / len(set1)

In [45]:
def score(stimulus,response):
    overlap=word_overlap(stimulus,response)
    if(overlap>0.9):
        return 4
    elif(overlap>0.75):
        return 3
    elif(overlap>0.5):
        return 2
    elif(overlap>0.3):
        return 1
    else:
        return 0

In [46]:
df["Score"] = df.apply(
    lambda row: score(row["clean_stimulus"], row["clean_original"]), axis=1
)
df.head(50)

,Sentence,Stimulus,Transcription Rater 1,Score,clean_stimulus,clean_original
0,1,Quiero cortarme el pelo (7),Quiero cortarme el pelo,3,quiero cortarme el pelo 7,quiero cortarme el pelo
1,2,El libro está en la mesa (7),El libro está en la mesa,3,el libro está en la mesa 7,el libro está en la mesa
2,3,El carro lo tiene Pedro (8),El carro lo tiene Pedro,3,el carro lo tiene pedro 8,el carro lo tiene pedro
3,4,El se ducha cada mañana (9),El se ducha cada mañana,3,el se ducha cada mañana 9,el se ducha cada mañana
4,5,¿Qué dice usted que va a hacer hoy? (9),Que dices ustedes se que van a hacer hoy?,1,qué dice usted que va a hacer hoy 9,que dices ustedes se que van a hacer hoy
5,6,Dudo que sepa manejar muy bien (10),Dudo que sepa manajar bien,2,dudo que sepa manejar muy bien 10,dudo que sepa manajar bien
6,7,Las calles de esta ciudad son muy anchas (11),Las calles de esta cuidad son muy anchas,3,las calles de esta ciudad son muy anchas 11,las calles de esta cuidad son muy anchas
7,8,Puede que llueva mañana todo el día (12),Puede que lleva mañana todo el día,2,puede que llueva mañana todo el día 12,puede que lleva mañana todo el día
8,9,Las casas son muy bonitas pero caras (12),Las casas son muy bonitas pero muy cadas,2,las casas son muy bonitas pero caras 12,las casas son muy bonitas pero muy cadas
9,10,Me gustan las películas que acaban bien (12),Me gustan las peliculas que acaban bien,2,me gustan las películas que acaban bien 12,me gustan las peliculas que acaban bien
10,11,El chico con el que yo salgo es español (13),El chico con yo salgo ...um.. está bien,2,el chico con el que yo salgo es español 13,el chico con yo salgo um está bien
11,12,Después de cenar me fui a dormir tranquilo (13),Despues de cenar me fui a dormir tranquilo,3,después de cenar me fui a dormir tranquilo 13,despues de cenar me fui a dormir tranquilo
12,13,Quiero una casa en la que vivan mis animales (14),Quiero una casa que vivan los animales,2,quiero una casa en la que vivan mis animales 14,quiero una casa que vivan los animales
13,14,A nosotros nos fascinan las fiestas grandiosas...,A nosotros ..nos fascina los fiestas grandiosos,1,a nosotros nos fascinan las fiestas grandiosas 14,a nosotros nos fascina los fiestas grandiosos
14,15,Ella sólo bebe cerveza y no come nada (15),Ella solo bebe cerveza y no come nada,3,ella sólo bebe cerveza y no come nada 15,ella solo bebe cerveza y no come nada
15,16,Me gustaría que el precio de las casas bajara ...,Me gustaría que las precios de las casas bajaron,2,me gustaría que el precio de las casas bajara 15,me gustaría que las precios de las casas bajaron
16,17,Cruza a la derecha y después sigue todo recto ...,Cruza a la derecha y sigue a la izquierda,2,cruza a la derecha y después sigue todo recto 15,cruza a la derecha y sigue a la izquierda
17,18,Ella ha terminado de pintar su apartamento (15),Ella ha terminado pintando su apartamento,2,ella ha terminado de pintar su apartamento 15,ella ha terminado pintando su apartamento
18,19,Me gustaría que empezara a hacer más calor pro...,Me gustaría se .. más calor,1,me gustaría que empezara a hacer más calor pro...,me gustaría se más calor
19,20,El niño al que se le murió el gato está triste...,El niño que se murió su gato es triste,2,el niño al que se le murió el gato está triste 16,el niño que se murió su gato es triste
20,21,Una amiga mía cuida a los niños de mi vecino (16),una amiga de mio cuida su... niños de vecino,2,una amiga mía cuida a los niños de mi vecino 16,una amiga de mio cuida su niños de vecino
21,22,El gato que era negro fue perseguido por el pe...,El gato que era negro era perseguido de(l) perro,2,el gato que era negro fue perseguido por el pe...,el gato que era negro era perseguido del perro
22,23,Antes de poder salir él tiene que limpiar su c...,Antes de salir el tiene que limpiar su cuarto,2,antes de poder salir él tiene que limpiar su c...,antes de salir el tiene que limpiar su cuarto
23,24,La cantidad de personas que fuman ha disminuid...,La cantidad de personas que fuman ha..desmenido,2,la cantidad de personas que fuman ha disminuid...,la cantidad de personas que fuman hadesmenido
24,25,Después de llegar a casa del trabajo tomé la c...,Despues de llegar a casa del trabajo...se...meh,1,después de llegar a casa del trabajo tomé la c...,despues de llegar a casa del trabajosemeh
25,26,El ladrón al que atrapó la policía era famoso ...,El ladrón que atrapó la policia era famoso,2,el ladrón al que atrapó la policía era famoso 17,el ladrón que atrapó la policia era famoso
26,27,Le pedí a un amigo que me ayudara con la tarea...,Le pedí a un amigo que me ayudara con la tarea,4,le pedí a un amigo que me ayudara con la tarea 17,le pedí a un amigo que me ayudara con la tarea
27,28,El examen no fue tan difícil como me habían di...,El examen no fue tan dificil como me decían,2,el examen no fue tan difícil como me habían di...,el examen no fue tan dificil como me decían
28,29,¿Serías tan amable de darme el libro que está ...,Serías tan amable pa'- darme el libro que está...,3,serías tan amable de darme el libro que está e...,serías tan amable pa darme el libro que está e...
29,30,Hay mucha gente que no toma nada para el desay...,Hay mucha genta que no to- toma nada para el d...,3,hay mucha gente que no toma nada para el desay...,hay mucha genta que no to toma nada para el de...

In [18]:
df.drop("Predicted_Score", axis=1, inplace=True)

In [47]:
df.head(30)

,Sentence,Stimulus,Transcription Rater 1,Score,clean_stimulus,clean_original
0,1,Quiero cortarme el pelo (7),Quiero cortarme el pelo,3,quiero cortarme el pelo 7,quiero cortarme el pelo
1,2,El libro está en la mesa (7),El libro está en la mesa,3,el libro está en la mesa 7,el libro está en la mesa
2,3,El carro lo tiene Pedro (8),El carro lo tiene Pedro,3,el carro lo tiene pedro 8,el carro lo tiene pedro
3,4,El se ducha cada mañana (9),El se ducha cada mañana,3,el se ducha cada mañana 9,el se ducha cada mañana
4,5,¿Qué dice usted que va a hacer hoy? (9),Que dices ustedes se que van a hacer hoy?,1,qué dice usted que va a hacer hoy 9,que dices ustedes se que van a hacer hoy
5,6,Dudo que sepa manejar muy bien (10),Dudo que sepa manajar bien,2,dudo que sepa manejar muy bien 10,dudo que sepa manajar bien
6,7,Las calles de esta ciudad son muy anchas (11),Las calles de esta cuidad son muy anchas,3,las calles de esta ciudad son muy anchas 11,las calles de esta cuidad son muy anchas
7,8,Puede que llueva mañana todo el día (12),Puede que lleva mañana todo el día,2,puede que llueva mañana todo el día 12,puede que lleva mañana todo el día
8,9,Las casas son muy bonitas pero caras (12),Las casas son muy bonitas pero muy cadas,2,las casas son muy bonitas pero caras 12,las casas son muy bonitas pero muy cadas
9,10,Me gustan las películas que acaban bien (12),Me gustan las peliculas que acaban bien,2,me gustan las películas que acaban bien 12,me gustan las peliculas que acaban bien
10,11,El chico con el que yo salgo es español (13),El chico con yo salgo ...um.. está bien,2,el chico con el que yo salgo es español 13,el chico con yo salgo um está bien
11,12,Después de cenar me fui a dormir tranquilo (13),Despues de cenar me fui a dormir tranquilo,3,después de cenar me fui a dormir tranquilo 13,despues de cenar me fui a dormir tranquilo
12,13,Quiero una casa en la que vivan mis animales (14),Quiero una casa que vivan los animales,2,quiero una casa en la que vivan mis animales 14,quiero una casa que vivan los animales
13,14,A nosotros nos fascinan las fiestas grandiosas...,A nosotros ..nos fascina los fiestas grandiosos,1,a nosotros nos fascinan las fiestas grandiosas 14,a nosotros nos fascina los fiestas grandiosos
14,15,Ella sólo bebe cerveza y no come nada (15),Ella solo bebe cerveza y no come nada,3,ella sólo bebe cerveza y no come nada 15,ella solo bebe cerveza y no come nada
15,16,Me gustaría que el precio de las casas bajara ...,Me gustaría que las precios de las casas bajaron,2,me gustaría que el precio de las casas bajara 15,me gustaría que las precios de las casas bajaron
16,17,Cruza a la derecha y después sigue todo recto ...,Cruza a la derecha y sigue a la izquierda,2,cruza a la derecha y después sigue todo recto 15,cruza a la derecha y sigue a la izquierda
17,18,Ella ha terminado de pintar su apartamento (15),Ella ha terminado pintando su apartamento,2,ella ha terminado de pintar su apartamento 15,ella ha terminado pintando su apartamento
18,19,Me gustaría que empezara a hacer más calor pro...,Me gustaría se .. más calor,1,me gustaría que empezara a hacer más calor pro...,me gustaría se más calor
19,20,El niño al que se le murió el gato está triste...,El niño que se murió su gato es triste,2,el niño al que se le murió el gato está triste 16,el niño que se murió su gato es triste
20,21,Una amiga mía cuida a los niños de mi vecino (16),una amiga de mio cuida su... niños de vecino,2,una amiga mía cuida a los niños de mi vecino 16,una amiga de mio cuida su niños de vecino
21,22,El gato que era negro fue perseguido por el pe...,El gato que era negro era perseguido de(l) perro,2,el gato que era negro fue perseguido por el pe...,el gato que era negro era perseguido del perro
22,23,Antes de poder salir él tiene que limpiar su c...,Antes de salir el tiene que limpiar su cuarto,2,antes de poder salir él tiene que limpiar su c...,antes de salir el tiene que limpiar su cuarto
23,24,La cantidad de personas que fuman ha disminuid...,La cantidad de personas que fuman ha..desmenido,2,la cantidad de personas que fuman ha disminuid...,la cantidad de personas que fuman hadesmenido
24,25,Después de llegar a casa del trabajo tomé la c...,Despues de llegar a casa del trabajo...se...meh,1,después de llegar a casa del trabajo tomé la c...,despues de llegar a casa del trabajosemeh
25,26,El ladrón al que atrapó la policía era famoso ...,El ladrón que atrapó la policia era famoso,2,el ladrón al que atrapó la policía era famoso 17,el ladrón que atrapó la policia era famoso
26,27,Le pedí a un amigo que me ayudara con la tarea...,Le pedí a un amigo que me ayudara con la tarea,4,le pedí a un amigo que me ayudara con la tarea 17,le pedí a un amigo que me ayudara con la tarea
27,28,El examen no fue tan difícil como me habían di...,El examen no fue tan dificil como me decían,2,el examen no fue tan difícil como me habían di...,el examen no fue tan dificil como me decían
28,29,¿Serías tan amable de darme el libro que está ...,Serías tan amable pa'- darme el libro que está...,3,serías tan amable de darme el libro que está e...,serías tan amable pa darme el libro que está e...
29,30,Hay mucha gente que no toma nada para el desay...,Hay mucha genta que no to- toma nada para el d...,3,hay mucha gente que no toma nada para el desay...,hay mucha genta que no to toma nada para el de...

In [22]:
df.to_excel("basic_score.xlsx", index=False)

### Rule Based+ML(Semantic) based Scoring

In [26]:
!pip install sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (5.3.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: torch>=1.11.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: numpy in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (2.2.4)
Requirement already satisfied: scikit-learn in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (1.16.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (4.13.2)
Requirement already satisfied: tqdm in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: colorama in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: click>=8.2.1 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
import sys
!"{sys.executable}" -m pip install sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.44.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (0.24.6)
Requirement already satisfied: torch>=1.11.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.2.2+cpu)
Requirement already satisfied: numpy in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.14.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.9.0)
Requirement already satisfied: tqdm in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: filelock in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.2)
Requirement already satisfied: sympy in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.2)
Requirement already satisfied: networkx in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: colorama in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.7.24)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.19.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2023.11.17)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shruti sachan\appdata\local\programs\python\python312\lib\site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Using cached sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-5.3.0

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: C:\Users\Shruti Sachan\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [48]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
model=SentenceTransformer('all-MiniLM-L6-v2')

C:\Users\Shruti Sachan\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [50]:
def semantic(s1,s2):
    emb1=model.encode(s1)
    emb2=model.encode(s2)
    sim=cosine_similarity([emb1],[emb2])[0][0]
    return sim

In [51]:
from difflib import SequenceMatcher
def edit_sim(s1,s2):
    return SequenceMatcher(None,s1,s2).ratio()

In [52]:
def missing_word(s1,s2):
    word1=set(s1.split())
    word2=set(s2.split())
    missing=len(word1-word2)
    return missing/len(word1)

In [53]:
def get_ngrams(text, n):
    words = text.split()
    return [" ".join(words[i:i+n]) for i in range(len(words)-n+1)]

In [54]:
def ngram_overlap(s1, s2, n=2):
    ngrams1 = set(get_ngrams(s1, n))
    ngrams2 = set(get_ngrams(s2, n))
    if len(ngrams1) == 0:
        return 0
    return len(ngrams1 & ngrams2) / len(ngrams1)

In [55]:
def length_ratio(s1, s2):
    if len(s1.split()) == 0:
        return 0
    return len(s2.split()) / len(s1.split())

In [56]:
def hybrid_score(stimulus, response):
    overlap = word_overlap(stimulus, response)
    semantic_sim = semantic(stimulus, response)
    length = length_ratio(stimulus, response)
    match = edit_sim(stimulus, response)
    bigram_score = ngram_overlap(stimulus, response, n=2)
    final = (
        0.2 * overlap +
        0.25 * semantic_sim +
        0.15 * length +
        0.2 * match +
        0.2 * bigram_score
    )
    if length < 0.6:
        final *= 0.75
    if missing_word(stimulus, response) > 0.4:
        final *= 0.75
    if semantic_sim > 0.9 and overlap > 0.85:
        return 4
    if final > 0.85:
        return 4
    elif final > 0.7:
        return 3
    elif final > 0.5:
        return 2
    elif final > 0.3:
        return 1
    else:
        return 0

In [57]:
df["Hybrid_Score"] = df.apply(
    lambda row: hybrid_score(row["clean_stimulus"], row["clean_original"]), axis=1
)

In [58]:
df[["Stimulus", "Transcription Rater 1", "Score", "Hybrid_Score"]].head(10)

,Stimulus,Transcription Rater 1,Score,Hybrid_Score
0,Quiero cortarme el pelo (7),Quiero cortarme el pelo,3,4
1,El libro está en la mesa (7),El libro está en la mesa,3,4
2,El carro lo tiene Pedro (8),El carro lo tiene Pedro,3,4
3,El se ducha cada mañana (9),El se ducha cada mañana,3,4
4,¿Qué dice usted que va a hacer hoy? (9),Que dices ustedes se que van a hacer hoy?,1,1
5,Dudo que sepa manejar muy bien (10),Dudo que sepa manajar bien,2,1
6,Las calles de esta ciudad son muy anchas (11),Las calles de esta cuidad son muy anchas,3,3
7,Puede que llueva mañana todo el día (12),Puede que lleva mañana todo el día,2,3
8,Las casas son muy bonitas pero caras (12),Las casas son muy bonitas pero muy cadas,2,3
9,Me gustan las películas que acaban bien (12),Me gustan las peliculas que acaban bien,2,3

In [59]:
df.head(30)

,Sentence,Stimulus,Transcription Rater 1,Score,clean_stimulus,clean_original,Hybrid_Score
0,1,Quiero cortarme el pelo (7),Quiero cortarme el pelo,3,quiero cortarme el pelo 7,quiero cortarme el pelo,4
1,2,El libro está en la mesa (7),El libro está en la mesa,3,el libro está en la mesa 7,el libro está en la mesa,4
2,3,El carro lo tiene Pedro (8),El carro lo tiene Pedro,3,el carro lo tiene pedro 8,el carro lo tiene pedro,4
3,4,El se ducha cada mañana (9),El se ducha cada mañana,3,el se ducha cada mañana 9,el se ducha cada mañana,4
4,5,¿Qué dice usted que va a hacer hoy? (9),Que dices ustedes se que van a hacer hoy?,1,qué dice usted que va a hacer hoy 9,que dices ustedes se que van a hacer hoy,1
5,6,Dudo que sepa manejar muy bien (10),Dudo que sepa manajar bien,2,dudo que sepa manejar muy bien 10,dudo que sepa manajar bien,1
6,7,Las calles de esta ciudad son muy anchas (11),Las calles de esta cuidad son muy anchas,3,las calles de esta ciudad son muy anchas 11,las calles de esta cuidad son muy anchas,3
7,8,Puede que llueva mañana todo el día (12),Puede que lleva mañana todo el día,2,puede que llueva mañana todo el día 12,puede que lleva mañana todo el día,3
8,9,Las casas son muy bonitas pero caras (12),Las casas son muy bonitas pero muy cadas,2,las casas son muy bonitas pero caras 12,las casas son muy bonitas pero muy cadas,3
9,10,Me gustan las películas que acaban bien (12),Me gustan las peliculas que acaban bien,2,me gustan las películas que acaban bien 12,me gustan las peliculas que acaban bien,3
10,11,El chico con el que yo salgo es español (13),El chico con yo salgo ...um.. está bien,2,el chico con el que yo salgo es español 13,el chico con yo salgo um está bien,1
11,12,Después de cenar me fui a dormir tranquilo (13),Despues de cenar me fui a dormir tranquilo,3,después de cenar me fui a dormir tranquilo 13,despues de cenar me fui a dormir tranquilo,4
12,13,Quiero una casa en la que vivan mis animales (14),Quiero una casa que vivan los animales,2,quiero una casa en la que vivan mis animales 14,quiero una casa que vivan los animales,2
13,14,A nosotros nos fascinan las fiestas grandiosas...,A nosotros ..nos fascina los fiestas grandiosos,1,a nosotros nos fascinan las fiestas grandiosas 14,a nosotros nos fascina los fiestas grandiosos,2
14,15,Ella sólo bebe cerveza y no come nada (15),Ella solo bebe cerveza y no come nada,3,ella sólo bebe cerveza y no come nada 15,ella solo bebe cerveza y no come nada,3
15,16,Me gustaría que el precio de las casas bajara ...,Me gustaría que las precios de las casas bajaron,2,me gustaría que el precio de las casas bajara 15,me gustaría que las precios de las casas bajaron,3
16,17,Cruza a la derecha y después sigue todo recto ...,Cruza a la derecha y sigue a la izquierda,2,cruza a la derecha y después sigue todo recto 15,cruza a la derecha y sigue a la izquierda,2
17,18,Ella ha terminado de pintar su apartamento (15),Ella ha terminado pintando su apartamento,2,ella ha terminado de pintar su apartamento 15,ella ha terminado pintando su apartamento,3
18,19,Me gustaría que empezara a hacer más calor pro...,Me gustaría se .. más calor,1,me gustaría que empezara a hacer más calor pro...,me gustaría se más calor,0
19,20,El niño al que se le murió el gato está triste...,El niño que se murió su gato es triste,2,el niño al que se le murió el gato está triste 16,el niño que se murió su gato es triste,2
20,21,Una amiga mía cuida a los niños de mi vecino (16),una amiga de mio cuida su... niños de vecino,2,una amiga mía cuida a los niños de mi vecino 16,una amiga de mio cuida su niños de vecino,1
21,22,El gato que era negro fue perseguido por el pe...,El gato que era negro era perseguido de(l) perro,2,el gato que era negro fue perseguido por el pe...,el gato que era negro era perseguido del perro,3
22,23,Antes de poder salir él tiene que limpiar su c...,Antes de salir el tiene que limpiar su cuarto,2,antes de poder salir él tiene que limpiar su c...,antes de salir el tiene que limpiar su cuarto,3
23,24,La cantidad de personas que fuman ha disminuid...,La cantidad de personas que fuman ha..desmenido,2,la cantidad de personas que fuman ha disminuid...,la cantidad de personas que fuman hadesmenido,3
24,25,Después de llegar a casa del trabajo tomé la c...,Despues de llegar a casa del trabajo...se...meh,1,después de llegar a casa del trabajo tomé la c...,despues de llegar a casa del trabajosemeh,1
25,26,El ladrón al que atrapó la policía era famoso ...,El ladrón que atrapó la policia era famoso,2,el ladrón al que atrapó la policía era famoso 17,el ladrón que atrapó la policia era famoso,3
26,27,Le pedí a un amigo que me ayudara con la tarea...,Le pedí a un amigo que me ayudara con la tarea,4,le pedí a un amigo que me ayudara con la tarea 17,le pedí a un amigo que me ayudara con la tarea,4
27,28,El examen no fue tan difícil como me habían di...,El examen no fue tan dificil como me decían,2,el examen no fue tan difícil como me habían di...,el examen no fue tan dificil como me decían,3
28,29,¿Serías tan amable de darme el libro que está ...,Serías tan amable pa'- darme el libro que está...,3,serías tan amable de darme el libro que está e...,serías tan amable pa darme el libro que está e...,4
29,30,Hay mucha gente que no toma nada para el desay...,Hay mucha genta que no to- toma nada para el d...,3,hay mucha gente que no toma nada para el desay...,hay mucha genta que no to toma nada para el de...,3

In [32]:
!pip install xlsxwriter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlsxwriter in c:\users\shruti sachan\appdata\roaming\python\python313\site-packages (3.2.9)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import sys
!"{sys.executable}" -m pip install xlsxwriter

Collecting xlsxwriter
  Using cached xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Using cached xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: C:\Users\Shruti Sachan\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [60]:
print(df.columns)

Index(['Sentence', 'Stimulus', 'Transcription Rater 1', 'Score',
       'clean_stimulus', 'clean_original', 'Hybrid_Score'],
      dtype='object')

In [75]:
import pandas as pd
xls = pd.ExcelFile("AutoEIT Sample Transcriptions for Scoring.xlsx")
with pd.ExcelWriter("final_output.xlsx") as writer:
    for sheet in xls.sheet_names[1:]:
        df = pd.read_excel(xls, sheet_name=sheet) 
        df["clean_stimulus"]=df["Stimulus"].apply(preprocess)
        df["clean_original"]=df["Transcription Rater 1"].apply(preprocess)
        df["Score"] = df.apply(
            lambda row: hybrid_score(row["clean_stimulus"], row["clean_original"]), axis=1
        )
        df.to_excel(writer, sheet_name=sheet, index=False)